# Generated by Django 4.2.1 on 2023-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("note", models.CharField(max_length=250)),
            ],
        ),
    ]
