# Generated by Django 4.2.1 on 2023-05-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='title',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='note',
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=250)),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.weekday')),
            ],
        ),
    ]
